### ISSUE TITLE
wrong gradient

### ISSUE THREAD

**Issue by ahmaddorri** [FunctorML/BellkorAlgorithm#1]
hello @dandxy89
I think  
b_u = 2 * error * (-1 + 2 * self.REGULARISATION.b_u * rs.b_u) 
is wrong
and 
b_u =  -2 * error  + 2 * self.REGULARISATION.b_u * rs.b_u 
is correct

**Comment by dandxy89** [comment]
Thanks, @ahmaddorri  - I'll take a look this evening.

**Comment by FK0512** [comment]
Hello @dandxy89,
Fiza this side,I want to discuss about the recommendation system .can you share your email  so that I can discuss with you.

**Comment by dandxy89** [comment]
@FK0512  What would you like to discuss?

This project is unmaintained - feel free to fork. Im happy to transfer ownership if you're interested.

**Comment by FK0512** [comment]
@dandxy89 I want to know how we can optimize the existing recommendation system so as to increase engagement .if I want to start by making a model,training it and using ensemble method for increasing sales and e commerce to a specific number .If we want to make customizable recommendation system according to company's requirements.

**Comment by dandxy89** [comment]
I would not recommend this repository. I'd personally familiarise yourself with 'modern' collaborative filtering and the underlying techniques. I fairly confident there are more prominent and well maintained open source alternatives to this that must be available to you and your team?

It'd personally start here:

- Github Topic: https://github.com/topics/recommendation-system?l=python
- And then immediately dive into this repository: https://github.com/recommenders-team/recommenders

Depending on your specific needs I'd recommend intially staying clear of NN based implementations until you've undertaken some initial invesitgations with alternatives.

A note on this repository: I never fully validated its effectiveness, furthermore, its worth noting that this implementation was highly tailored to the original challenge and may not be relevent to your application/need.
